import type { EndpointDefinition } from './types.js';

function defineEndpoint(definition: EndpointDefinition): EndpointDefinition {
  return definition;
}

export const endpointDefinitions: EndpointDefinition[] = [
  defineEndpoint({
    id: 'auth-validate',
    framework: 'auth',
    resource: 'auth',
    operation: 'validate',
    label: 'Validate credentials',
    method: 'GET',
    pathTemplate: '/app-automate/plan.json',
    description: 'Validate credentials and fetch current plan summary.',
    requestKind: 'json',
  }),
  defineEndpoint({
    id: 'auth-usage',
    framework: 'auth',
    resource: 'plan',
    operation: 'usage',
    label: 'Usage details',
    method: 'GET',
    pathTemplate: '/app-automate/current_parallel_queue_usage',
    description: 'Fetch real-time queue and parallel usage details.',
    requestKind: 'json',
  }),
  defineEndpoint({
    id: 'appium-apps-upload',
    framework: 'appium',
    resource: 'apps',
    operation: 'upload',
    label: 'Upload app',
    method: 'POST',
    pathTemplate: '/app-automate/upload',
    description: 'Upload an Appium app from file system or URL.',
    requestKind: 'multipart',
    upload: { fileFieldName: 'file', urlFieldName: 'url' },
  }),
  defineEndpoint({
    id: 'appium-apps-list',
    framework: 'appium',
    resource: 'apps',
    operation: 'list',
    label: 'List apps',
    method: 'GET',
    pathTemplate: '/app-automate/recent_apps',
    description: 'List recently uploaded Appium apps.',
    requestKind: 'json',
    queryParams: ['custom_id'],
  }),
  defineEndpoint({
    id: 'appium-apps-list-group',
    framework: 'appium',
    resource: 'apps',
    operation: 'list-group',
    label: 'List group apps',
    method: 'GET',
    pathTemplate: '/app-automate/recent_group_apps',
    description: 'List recently uploaded Appium apps for the current group.',
    requestKind: 'json',
    queryParams: ['limit'],
  }),
  defineEndpoint({
    id: 'appium-apps-delete',
    framework: 'appium',
    resource: 'apps',
    operation: 'delete',
    label: 'Delete app',
    method: 'DELETE',
    pathTemplate: '/app-automate/app/delete/{appID}',
    description: 'Delete an uploaded Appium app.',
    requestKind: 'json',
    pathParams: ['appID'],
  }),
  defineEndpoint({
    id: 'appium-builds-list',
    framework: 'appium',
    resource: 'builds',
    operation: 'list',
    label: 'List builds',
    method: 'GET',
    pathTemplate: '/app-automate/builds.json',
    description: 'List recent Appium builds.',
    requestKind: 'json',
    queryParams: ['limit', 'offset', 'status', 'projectId'],
  }),
  defineEndpoint({
    id: 'appium-builds-get',
    framework: 'appium',
    resource: 'builds',
    operation: 'get',
    label: 'Get build details',
    method: 'GET',
    pathTemplate: '/app-automate/builds/{buildID}/sessions.json',
    description: 'Get Appium build details and included sessions.',
    requestKind: 'json',
    pathParams: ['buildID'],
  }),
  defineEndpoint({
    id: 'appium-sessions-list',
    framework: 'appium',
    resource: 'sessions',
    operation: 'list',
    label: 'List sessions',
    method: 'GET',
    pathTemplate: '/app-automate/builds/{buildID}/sessions.json',
    description: 'List Appium sessions under a build.',
    requestKind: 'json',
    pathParams: ['buildID'],
    queryParams: ['limit', 'offset', 'status'],
  }),
  defineEndpoint({
    id: 'appium-sessions-get',
    framework: 'appium',
    resource: 'sessions',
    operation: 'get',
    label: 'Get session details',
    method: 'GET',
    pathTemplate: '/app-automate/sessions/{sessionID}.json',
    description: 'Get Appium session details.',
    requestKind: 'json',
    pathParams: ['sessionID'],
  }),
  defineEndpoint({
    id: 'appium-sessions-update-status',
    framework: 'appium',
    resource: 'sessions',
    operation: 'update-status',
    label: 'Update session status',
    method: 'PUT',
    pathTemplate: '/app-automate/sessions/{sessionID}.json',
    description: 'Update Appium session status and reason.',
    requestKind: 'json',
    pathParams: ['sessionID'],
  }),
  ...defineV2ArtifactEndpoints('maestro', '/app-automate/maestro/v2', true),
  ...defineV2BuildEndpoints('maestro', '/app-automate/maestro/v2'),
  ...defineV2ArtifactEndpoints('espresso', '/app-automate/espresso/v2', true),
  ...defineV2BuildEndpoints('espresso', '/app-automate/espresso/v2'),
  ...defineV2ArtifactEndpoints(
    'flutter-android',
    '/app-automate/flutter-integration-tests/v2/android',
    true,
  ),
  ...defineV2BuildEndpoints(
    'flutter-android',
    '/app-automate/flutter-integration-tests/v2/android',
  ),
  ...defineFlutterIosEndpoints(),
  ...defineDetoxEndpoints(),
  ...defineV2ArtifactEndpoints('xcuitest', '/app-automate/xcuitest/v2', true),
  ...defineV2BuildEndpoints('xcuitest', '/app-automate/xcuitest/v2'),
  ...defineMediaEndpoints(),
];

function defineV2ArtifactEndpoints(
  framework:
    | 'maestro'
    | 'espresso'
    | 'flutter-android'
    | 'xcuitest',
  basePath: string,
  includeApps: boolean,
): EndpointDefinition[] {
  const endpoints: EndpointDefinition[] = [];

  if (includeApps) {
    endpoints.push(
      defineEndpoint({
        id: `${framework}-apps-upload`,
        framework,
        resource: 'apps',
        operation: 'upload',
        label: 'Upload app',
        method: 'POST',
        pathTemplate: `${basePath}/app`,
        description: `Upload an app for ${framework}.`,
        requestKind: 'multipart',
        upload: { fileFieldName: 'file', urlFieldName: 'url' },
      }),
      defineEndpoint({
        id: `${framework}-apps-list`,
        framework,
        resource: 'apps',
        operation: 'list',
        label: 'List apps',
        method: 'GET',
        pathTemplate: `${basePath}/apps`,
        description: `List apps for ${framework}.`,
        requestKind: 'json',
        queryParams: ['custom_id', 'scope', 'limit'],
      }),
      defineEndpoint({
        id: `${framework}-apps-get`,
        framework,
        resource: 'apps',
        operation: 'get',
        label: 'Get app details',
        method: 'GET',
        pathTemplate: `${basePath}/apps/{appId}`,
        description: `Get app details for ${framework}.`,
        requestKind: 'json',
        pathParams: ['appId'],
      }),
      defineEndpoint({
        id: `${framework}-apps-delete`,
        framework,
        resource: 'apps',
        operation: 'delete',
        label: 'Delete app',
        method: 'DELETE',
        pathTemplate: `${basePath}/apps/{appId}`,
        description: `Delete an uploaded app for ${framework}.`,
        requestKind: 'json',
        pathParams: ['appId'],
      }),
    );
  }

  endpoints.push(
    defineEndpoint({
      id: `${framework}-tests-upload`,
      framework,
      resource: 'test-suites',
      operation: 'upload',
      label: 'Upload test suite',
      method: 'POST',
      pathTemplate: `${basePath}/test-suite`,
      description: `Upload a test suite for ${framework}.`,
      requestKind: 'multipart',
      upload: { fileFieldName: 'file', urlFieldName: 'url' },
    }),
    defineEndpoint({
      id: `${framework}-tests-list`,
      framework,
      resource: 'test-suites',
      operation: 'list',
      label: 'List test suites',
      method: 'GET',
      pathTemplate: `${basePath}/test-suites`,
      description: `List test suites for ${framework}.`,
      requestKind: 'json',
      queryParams: ['custom_id', 'scope', 'limit'],
    }),
    defineEndpoint({
      id: `${framework}-tests-get`,
      framework,
      resource: 'test-suites',
      operation: 'get',
      label: 'Get test suite details',
      method: 'GET',
      pathTemplate: `${basePath}/test-suites/{testSuiteId}`,
      description: `Get test suite details for ${framework}.`,
      requestKind: 'json',
      pathParams: ['testSuiteId'],
    }),
    defineEndpoint({
      id: `${framework}-tests-delete`,
      framework,
      resource: 'test-suites',
      operation: 'delete',
      label: 'Delete test suite',
      method: 'DELETE',
      pathTemplate: `${basePath}/test-suites/{testSuiteId}`,
      description: `Delete a test suite for ${framework}.`,
      requestKind: 'json',
      pathParams: ['testSuiteId'],
    }),
  );

  return endpoints;
}

function defineV2BuildEndpoints(
  framework: 'maestro' | 'espresso' | 'flutter-android' | 'xcuitest',
  basePath: string,
): EndpointDefinition[] {
  return [
    defineEndpoint({
      id: `${framework}-builds-run`,
      framework,
      resource: 'builds',
      operation: 'run',
      label: 'Execute build',
      method: 'POST',
      pathTemplate: `${basePath}/build`,
      description: `Execute a ${framework} build.`,
      requestKind: 'json',
    }),
    defineEndpoint({
      id: `${framework}-builds-list`,
      framework,
      resource: 'builds',
      operation: 'list',
      label: 'List builds',
      method: 'GET',
      pathTemplate: `${basePath}/builds`,
      description: `List recent ${framework} builds.`,
      requestKind: 'json',
      queryParams: ['project'],
    }),
    defineEndpoint({
      id: `${framework}-builds-get`,
      framework,
      resource: 'builds',
      operation: 'get',
      label: 'Get build status',
      method: 'GET',
      pathTemplate: `${basePath}/builds/{buildId}`,
      description: `Get ${framework} build status.`,
      requestKind: 'json',
      pathParams: ['buildId'],
    }),
    defineEndpoint({
      id: `${framework}-builds-stop`,
      framework,
      resource: 'builds',
      operation: 'stop',
      label: 'Stop build',
      method: 'POST',
      pathTemplate: `${basePath}/builds/{buildId}/stop`,
      description: `Stop a running ${framework} build.`,
      requestKind: 'json',
      pathParams: ['buildId'],
    }),
    defineEndpoint({
      id: `${framework}-sessions-get`,
      framework,
      resource: 'sessions',
      operation: 'get',
      label: 'Get session details',
      method: 'GET',
      pathTemplate: `${basePath}/builds/{buildId}/sessions/{sessionId}`,
      description: `Get ${framework} session details.`,
      requestKind: 'json',
      pathParams: ['buildId', 'sessionId'],
    }),
  ];
}

function defineFlutterIosEndpoints(): EndpointDefinition[] {
  return [
    defineEndpoint({
      id: 'flutter-ios-packages-upload',
      framework: 'flutter-ios',
      resource: 'test-packages',
      operation: 'upload',
      label: 'Upload test package',
      method: 'POST',
      pathTemplate: '/app-automate/flutter-integration-tests/v2/ios/test-package',
      description: 'Upload a Flutter iOS test package.',
      requestKind: 'multipart',
      upload: { fileFieldName: 'file' },
    }),
    defineEndpoint({
      id: 'flutter-ios-packages-list',
      framework: 'flutter-ios',
      resource: 'test-packages',
      operation: 'list',
      label: 'List test packages',
      method: 'GET',
      pathTemplate: '/app-automate/flutter-integration-tests/v2/ios/test-packages',
      description: 'List Flutter iOS test packages.',
      requestKind: 'json',
      queryParams: ['custom_id', 'scope', 'limit'],
    }),
    defineEndpoint({
      id: 'flutter-ios-packages-get',
      framework: 'flutter-ios',
      resource: 'test-packages',
      operation: 'get',
      label: 'Get test package details',
      method: 'GET',
      pathTemplate: '/app-automate/flutter-integration-tests/v2/ios/test-packages/{testPackageId}',
      description: 'Get Flutter iOS test package details.',
      requestKind: 'json',
      pathParams: ['testPackageId'],
    }),
    defineEndpoint({
      id: 'flutter-ios-packages-delete',
      framework: 'flutter-ios',
      resource: 'test-packages',
      operation: 'delete',
      label: 'Delete test package',
      method: 'DELETE',
      pathTemplate: '/app-automate/flutter-integration-tests/v2/ios/test-packages/{testPackageId}',
      description: 'Delete a Flutter iOS test package.',
      requestKind: 'json',
      pathParams: ['testPackageId'],
    }),
    defineEndpoint({
      id: 'flutter-ios-builds-run',
      framework: 'flutter-ios',
      resource: 'builds',
      operation: 'run',
      label: 'Execute build',
      method: 'POST',
      pathTemplate: '/app-automate/flutter-integration-tests/v2/ios/build',
      description: 'Execute a Flutter iOS build.',
      requestKind: 'json',
    }),
    defineEndpoint({
      id: 'flutter-ios-builds-list',
      framework: 'flutter-ios',
      resource: 'builds',
      operation: 'list',
      label: 'List builds',
      method: 'GET',
      pathTemplate: '/app-automate/flutter-integration-tests/v2/ios/builds',
      description: 'List Flutter iOS builds.',
      requestKind: 'json',
      queryParams: ['project'],
    }),
    defineEndpoint({
      id: 'flutter-ios-builds-get',
      framework: 'flutter-ios',
      resource: 'builds',
      operation: 'get',
      label: 'Get build status',
      method: 'GET',
      pathTemplate: '/app-automate/flutter-integration-tests/v2/ios/builds/{buildId}',
      description: 'Get Flutter iOS build status.',
      requestKind: 'json',
      pathParams: ['buildId'],
    }),
    defineEndpoint({
      id: 'flutter-ios-builds-stop',
      framework: 'flutter-ios',
      resource: 'builds',
      operation: 'stop',
      label: 'Stop build',
      method: 'POST',
      pathTemplate: '/app-automate/flutter-integration-tests/v2/ios/builds/{buildId}/stop',
      description: 'Stop a Flutter iOS build.',
      requestKind: 'json',
      pathParams: ['buildId'],
    }),
    defineEndpoint({
      id: 'flutter-ios-sessions-get',
      framework: 'flutter-ios',
      resource: 'sessions',
      operation: 'get',
      label: 'Get session details',
      method: 'GET',
      pathTemplate:
        '/app-automate/flutter-integration-tests/v2/ios/builds/{buildId}/sessions/{sessionId}',
      description: 'Get Flutter iOS session details.',
      requestKind: 'json',
      pathParams: ['buildId', 'sessionId'],
    }),
  ];
}

function defineDetoxEndpoints(): EndpointDefinition[] {
  return [
    defineEndpoint({
      id: 'detox-android-apps-upload',
      framework: 'detox-android',
      resource: 'apps',
      operation: 'upload',
      label: 'Upload app',
      method: 'POST',
      pathTemplate: '/app-automate/detox/v2/android/app',
      description: 'Upload a Detox Android app.',
      requestKind: 'multipart',
      upload: { fileFieldName: 'file', urlFieldName: 'url' },
    }),
    defineEndpoint({
      id: 'detox-android-app-client-upload',
      framework: 'detox-android',
      resource: 'app-client',
      operation: 'upload',
      label: 'Upload app client',
      method: 'POST',
      pathTemplate: '/app-automate/detox/v2/android/app-client',
      description: 'Upload a Detox Android app client bundle.',
      requestKind: 'multipart',
      upload: { fileFieldName: 'file', urlFieldName: 'url' },
    }),
    defineEndpoint({
      id: 'detox-android-sessions-get',
      framework: 'detox-android',
      resource: 'sessions',
      operation: 'get',
      label: 'Get session details',
      method: 'GET',
      pathTemplate: '/app-automate/detox/v2/android/sessions/{sessionID}.json',
      description: 'Get Detox Android session details.',
      requestKind: 'json',
      pathParams: ['sessionID'],
    }),
  ];
}

function defineMediaEndpoints(): EndpointDefinition[] {
  return [
    defineEndpoint({
      id: 'media-upload',
      framework: 'media',
      resource: 'media',
      operation: 'upload',
      label: 'Upload media',
      method: 'POST',
      pathTemplate: '/app-automate/upload-media',
      description: 'Upload media for App Automate tests.',
      requestKind: 'multipart',
      upload: { fileFieldName: 'file' },
    }),
    defineEndpoint({
      id: 'media-list',
      framework: 'media',
      resource: 'media',
      operation: 'list',
      label: 'List media',
      method: 'GET',
      pathTemplate: '/app-automate/recent_media_files',
      description: 'List recently uploaded media files.',
      requestKind: 'json',
      queryParams: ['custom_id'],
    }),
    defineEndpoint({
      id: 'media-list-group',
      framework: 'media',
      resource: 'media',
      operation: 'list-group',
      label: 'List group media',
      method: 'GET',
      pathTemplate: '/app-automate/recent_group_media',
      description: 'List recently uploaded group media files.',
      requestKind: 'json',
      queryParams: ['limit'],
    }),
    defineEndpoint({
      id: 'media-delete',
      framework: 'media',
      resource: 'media',
      operation: 'delete',
      label: 'Delete media',
      method: 'DELETE',
      pathTemplate: '/app-automate/custom_media/delete/{media_id}',
      description: 'Delete an uploaded media file.',
      requestKind: 'json',
      pathParams: ['media_id'],
    }),
  ];
}
