export { AuthService } from './auth/AuthService.js';
export { BrowserStackHttpClient } from './api/http/BrowserStackHttpClient.js';
export { BrowserStackApiError } from './api/http/errors.js';
export { buildMultipartPayload } from './api/http/multipart.js';
export { normalizeArtifact, normalizeArtifactCollection, normalizeBuildCollection, normalizeBuildSummary, normalizeSessionCollection, normalizeSessionSummary } from './api/normalizers/common.js';
export { EndpointRegistry } from './api/registry/EndpointRegistry.js';
export { endpointDefinitions } from './api/registry/definitions.js';
export type { EndpointDefinition, ResolvedEndpoint } from './api/registry/types.js';
export { CommandRuntime } from './cli/context.js';
export { Output } from './cli/output.js';
export { createProgram } from './cli/program.js';
export { runCli } from './cli/runCli.js';
export { getConfigDir, getConfigPath, getEncryptedSessionPath, getLastResponsePath, getPlainSessionPath } from './config/paths.js';
export { frameworkDescriptors, getFrameworkDescriptor, validateUploadPath } from './services/frameworkConfigs.js';
export { ResourceService } from './services/ResourceService.js';
export { SessionRepository } from './storage/SessionRepository.js';
export type { CredentialStore } from './storage/CredentialStore.js';
export type * from './types/domain.js';
